/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "RSAPrivateKey"
 * 	found in "rsa.asn1"
 */

#ifndef	_OtherPrimeInfo_H_
#define	_OtherPrimeInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtherPrimeInfo */
typedef struct OtherPrimeInfo {
	INTEGER_t	 prime;
	INTEGER_t	 exponent;
	INTEGER_t	 coefficient;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherPrimeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherPrimeInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherPrimeInfo_H_ */
#include <asn_internal.h>
