/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "RSAPrivateKey"
 * 	found in "rsa.asn1"
 */

#include "OtherPrimeInfo.h"

static asn_TYPE_member_t asn_MBR_OtherPrimeInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, prime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, exponent),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exponent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, coefficient),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"coefficient"
		},
};
static ber_tlv_tag_t asn_DEF_OtherPrimeInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_OtherPrimeInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* prime at 22 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* exponent at 23 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* coefficient at 25 */
};
static asn_SEQUENCE_specifics_t asn_SPC_OtherPrimeInfo_specs_1 = {
	sizeof(struct OtherPrimeInfo),
	offsetof(struct OtherPrimeInfo, _asn_ctx),
	asn_MAP_OtherPrimeInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_OtherPrimeInfo = {
	"OtherPrimeInfo",
	"OtherPrimeInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_OtherPrimeInfo_tags_1,
	sizeof(asn_DEF_OtherPrimeInfo_tags_1)
		/sizeof(asn_DEF_OtherPrimeInfo_tags_1[0]), /* 1 */
	asn_DEF_OtherPrimeInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_OtherPrimeInfo_tags_1)
		/sizeof(asn_DEF_OtherPrimeInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_OtherPrimeInfo_1,
	3,	/* Elements count */
	&asn_SPC_OtherPrimeInfo_specs_1	/* Additional specs */
};

